
<div id="wrapper">

	<div id="header">
		<div id="header-left"><a href="index.php" id="status-link"><img src="themes/nervecenter/images/transparent.gif" border="0"></img></a></div>
		<div id="header-right">
			<div class="container">
				<div class="left"></div>
				<div class="right">
					<div id="hostname">
						
					</div>
				</div>
			</div>
		</div>
	</div> <!-- Header DIV -->
	<div id="content">
		<div id="left">
			<div id="navigation" style="z-index:1000">
				<ul id="menu">
					<li class="firstdrop">
						<div>系&nbsp;&nbsp;统</div>
						<ul class="subdrop">
							<li><a href="system.php" class="navlnk">基本设置</a></li>
							<li><a href="system_advanced.php" class="navlnk">高级设置</a></li>
							<li><a href="system_firmware.php" class="navlnk">固件升级</a></li>
						</ul>
					</li>
					<li class="drop">
						<div>网络设置</div>
						<ul class="subdrop">
							<li><a href="network.php" class="navlnk">网络设置</a></li>
							<li><a href="interfaces_wan.php" class="navlnk">WAN</a></li>
							<li><a href="interfaces_lan.php" class="navlnk">LAN</a></li>
						</ul>
					</li>
					<li class="drop">
						<div>无线设置</div>
						<ul class="subdrop">
							<li><a href="interfaces_wifi.php" class="navlnk">无线接口</a></li>
							<li><a href="interfaces_vap.php" class="navlnk">无线网络</a></li>
						</ul>
					</li>
					<li class="drop">
						<div>服&nbsp;&nbsp;务</div>
						<ul class="subdrop">
							<li><a href="services_dhcp.php" class="navlnk">DHCP服务</a></li>
						</ul>
					</li>
					<li class="drop">
						<div>状&nbsp;&nbsp;态</div>
						<ul class="subdrop">
							<li><a href="diag_dhcp_leases.php" class="navlnk">DHCP客户列表</a></li>
							<li><a href="status_interfaces.php" class="navlnk">有线接口</a></li>
							<li><a href="status_interfaces_wifi.php" class="navlnk">无线接口</a></li>
							<li><a href="status_wifi_users.php" class="navlnk">无线用户</a></li>
							<li><a href="index.php" class="navlnk">系统</a></li>
							<li><a href="diag_logs.php" class="navlnk">系统日志</a></li>
						</ul>
					</li>
					<li class="lastdrop">
						<div>诊&nbsp;&nbsp;断</div>
						<ul id="diag" class="subdrop">
							<li><a href="diag_arp.php" class="navlnk">ARP表</a></li>
							<li><a href="diag_routes.php" class="navlnk">路由表</a></li>
							<li><a href="diag_defaults.php" class="navlnk">出厂设置</a></li>
							<li><a href="reboot.php" class="navlnk">重启系统</a></li>
							<li><a href="diag_ping.php" class="navlnk">Ping</a></li>
							<li><a href="diag_traceroute.php" class="navlnk">Traceroute</a></li>
						</ul>
					</li>
				</ul>
			</div>

		</div> <!-- Left DIV -->

		<div id="right">

